#!/bin/zsh
# name: bootstrap
# author: Wil Hall
# email: wil@wilhall.com

if [ "$#" -ne 1 ] && [ ! -f "$HOME/.auth" ]; then
  echo "Usage: ./bootstrap <DOTFILES_GITHUB_PERSONAL_ACCESS_TOKEN>"
  exit 1
fi

DOTFILES_GITHUB_PERSONAL_ACCESS_TOKEN=$1
SETUP_HOMEBREW=false

create_auth_dotfile() {
  if [ ! -f "$HOME/.auth" ]; then
    SETUP_HOMEBREW=true
  cat > "$HOME/.auth" <<- OUT
export HOMEBREW_GITHUB_API_TOKEN=$DOTFILES_GITHUB_PERSONAL_ACCESS_TOKEN
OUT
  fi
}

install_xcode_clt() {
  xcode-select -p 1>/dev/null
  if [[ $? != 0 ]]; then
    xcode-select --install
  fi
}

install_homebrew() {
  which -s brew
  if [[ $? != 0 ]]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

install_homebrew_bundle() { 
  if [[ $SETUP_HOMEBREW == true ]]; then
    brew tap homebrew/bundle
    brew bundle
  fi
}

install_gemfile_bundle() {
  bundle install --system
}

symlink_dotfiles() {
  ln -sfn $HOME/.dotfiles/.* $HOME/
  mkdir -p $HOME/.config && ln -sfn $HOME/.dotfiles/_config/* $HOME/.config
}

copy_ssh_settings() {
  mkdir -p $HOME/.ssh && rsync -u $HOME/.dotfiles/_ssh $HOME/.ssh
}

make_workspace() {
  mkdir -p $HOME/workspace/utils
}

make_user_bin() {
  mkdir -p $HOME/bin
  rsync -u $HOME/.dotfiles/bin $HOME/bin
}

restore_user_defaults() {
  $HOME/.dotfiles/applications/dx --restore-all
}

setup_vim() {
 vim -c 'PlugUpdate' -c 'CocUpdate' -c 'q!' -c 'q!'
}

set_default_shell() {
  sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
}

install_fonts() {
  find . -name "*.[ot]tf" -type f -exec cp {} "$HOME/Library/Fonts" \; 
}

configure_sublime_merge() {
  ln -s "/Applications/Sublime Merge.app/Contents/SharedSupport/bin/smerge" /usr/local/bin/smerge
}

install_athame() {
  if [ ! -f "$HOME/bin/azsh" ]; then
    git clone --recursive http://github.com/ardagnir/athame $HOME/workspace/utils/athame && cd $HOME/workspace/utils/athame && mkdir -p $HOME/.athame && ./zsh_athame_setup.sh --prefix=$HOME/.athame/ --vimbin=$(which nvim) && mv /usr/local/bin/zsh /usr/local/bin/_zsh && ln -s $HOME/.athame/bin/zsh /usr/local/bin/zsh && ln -s $HOME/.athame/bin/zsh $HOME/bin/azsh
  fi
}

install_tpm() {
  git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
}

bootstrap() {
  make_workspace
  make_user_bin
  copy_ssh_settings
  install_fonts
  create_auth_dotfile
  symlink_dotfiles
  install_xcode_clt
  install_homebrew
  install_homebrew_bundle
  set_default_shell
  install_gemfile_bundle
  restore_user_defaults
  setup_vim
  configure_sublime_merge
  #install_athame
  install_tpm
}

bootstrap
