#!/usr/bin/env bash

# $1 - Previous HEAD
# $2 - New HEAD
# $3 - `1` if checking out a branch, otherwise `0`
if [ '1' == $3 ]
then
    echo 'Branch changed - running pnpm install'
    pnpm install
fi
